export function potRank(p){return p==="A"?0:p==="B"?1:2;}
export function stableSortDocs(docs){return [...docs].sort((a,b)=>(a.city||"").localeCompare(b.city||"")||(a.sector||"").localeCompare(b.sector||"")||potRank(a.potential)-potRank(b.potential)||(a.name||"").localeCompare(b.name||""));}
export function clamp(n,a,b){return Math.max(a,Math.min(b,n));}
export function normalizeText(v){return(v??"").toString().trim().replace(/\s+/g," ").replace(/['']/g,"'").normalize("NFD").replace(/[\u0300-\u036f]/g,"");}
export function normalizeKey(v){return normalizeText(v).toLowerCase().replace(/[^a-z0-9]/g,"");}
export const CITY_ALIASES={rabat:"Rabat",temara:"Temara",skhirattemara:"Temara",skhirat:"Temara",sale:"Salé",kenitra:"Kénitra",casablanca:"Casablanca",casa:"Casablanca",mohammedia:"Mohammedia",marrakech:"Marrakech",agadir:"Agadir",fes:"Fès",fez:"Fès",meknes:"Meknès",tanger:"Tanger",oujda:"Oujda",tetouan:"Tétouan",tetouane:"Tétouan",eljadida:"El Jadida",jadida:"El Jadida",safi:"Safi"};
export function normalizeCity(v){const raw=normalizeText(v);if(!raw)return"";const key=normalizeKey(raw);return CITY_ALIASES[key]||raw.replace(/\b\w/g,m=>m.toUpperCase());}
export function looksLikeCity(v){const c=normalizeCity(v);return["Rabat","Temara","Salé","Kénitra","Casablanca","Mohammedia","Marrakech","Agadir","Fès","Meknès","Tanger","Oujda","Tétouan","El Jadida","Safi"].includes(c);}
export function normalizePotential(v){const s=normalizeText(v).toUpperCase();if(!s)return"B";if(s.startsWith("A"))return"A";if(s.startsWith("B"))return"B";if(s.startsWith("C"))return"C";return"B";}
export const COLUMN_ALIASES={id:["id","code","n","numero","num"],name:["name","nom","medecin","médecin","docteur","doctor","nommedecin","dr"],city:["city","ville","localite","zone","region"],sector:["sector","secteur","quartier","delegation","territoire"],potential:["potential","potentiel","segment","classe","priorite"],phone:["phone","telephone","tel","gsm","mobile"],email:["email","mail","e-mail"],activite:["activite","activité","statut","type","cabinet"],specialite:["specialite","spécialité","specialty","sp"]};
export function findColumnIndex(headers,aliases){const nh=headers.map(h=>normalizeKey(h));for(const a of aliases){const k=normalizeKey(a);const e=nh.findIndex(h=>h===k);if(e>=0)return e;}for(const a of aliases){const k=normalizeKey(a);const c=nh.findIndex(h=>h.includes(k)||k.includes(h));if(c>=0)return c;}return -1;}
export function buildHeaderMap(headers){const m={id:findColumnIndex(headers,COLUMN_ALIASES.id),name:findColumnIndex(headers,COLUMN_ALIASES.name),city:findColumnIndex(headers,COLUMN_ALIASES.city),sector:findColumnIndex(headers,COLUMN_ALIASES.sector),potential:findColumnIndex(headers,COLUMN_ALIASES.potential),phone:findColumnIndex(headers,COLUMN_ALIASES.phone),email:findColumnIndex(headers,COLUMN_ALIASES.email),activite:findColumnIndex(headers,COLUMN_ALIASES.activite),specialite:findColumnIndex(headers,COLUMN_ALIASES.specialite)};if(m.city<0&&m.sector>=0)m.city=m.sector;return m;}
export function valueAt(row,idx){if(idx<0)return"";return row[idx]??"";}
